package com.dreamer.mybudget;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DETAIL.
 */
public class Detail {

    private Long did;
    /** Not-null value. */
    private String io;
    private long time;
    private int price;
    /** Not-null value. */
    private String type;
    private String mark;

    public Detail() {
    }

    public Detail(Long did) {
        this.did = did;
    }

    public Detail(Long did, String io, long time, int price, String type, String mark) {
        this.did = did;
        this.io = io;
        this.time = time;
        this.price = price;
        this.type = type;
        this.mark = mark;
    }

    public Long getDid() {
        return did;
    }

    public void setDid(Long did) {
        this.did = did;
    }

    /** Not-null value. */
    public String getIo() {
        return io;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIo(String io) {
        this.io = io;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

}
